# Omakase Ruby styling for Rails.
inherit_gem:
  rubocop-rails-omakase: "rubocop.yml"

# Overwrite or add rules to create your own house style.
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
# Omakase Ruby styling for Rails.
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "config/initializers/devise.rb"
    - "config/environments/*.rb"
    - "Gemfile"
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude: